# Test GitHub action

name: Test GitHub Action
on: [push]
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test Action using default filename
      id: pom-details
      uses: ./ # Local action

    - name: Test values 1
      run: |
        ${{ steps.pom-details.outputs.current_version == '1.11.3.Final' }} && \
        ${{ steps.pom-details.outputs.project_group == 'org.acme' }} && \
        ${{ steps.pom-details.outputs.project_name == 'code-with-quarkus' }} && \
        ${{ steps.pom-details.outputs.quarkus_extensions == 'io.quarkus:quarkus-arc,io.quarkus:quarkus-junit5' }}

    - name: Test Action using provided filename
      id: pom-details-filename
      uses: ./ # Local action
      with:
        filename: pom.xml

    - name: Test values 2
      run: |
        ${{ steps.pom-details.outputs.current_version == '1.11.3.Final' }} && \
        ${{ steps.pom-details.outputs.project_group == 'org.acme' }} && \
        ${{ steps.pom-details.outputs.project_name == 'code-with-quarkus' }} && \
        ${{ steps.pom-details.outputs.quarkus_extensions == 'io.quarkus:quarkus-arc,io.quarkus:quarkus-junit5' }}

    - name: Test values for failure
      run: |
        ! [[ ${{ steps.pom-details.outputs.current_version == '1.11.2.Final' }} && \ # Modified
        ${{ steps.pom-details.outputs.project_group == 'org.acme' }} && \
        ${{ steps.pom-details.outputs.project_name == 'code-with-quarkus' }} && \
        ${{ steps.pom-details.outputs.quarkus_extensions == 'io.quarkus:quarkus-arc,io.quarkus:quarkus-junit5' }} ]]