# Test GitHub action

name: Test GitHub Action
on: [push]
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test Action using default filename
      id: pom-details
      uses: ./ # Local action

    - name: Check values
      run: |
        
        echo ${{ steps.pom-details.outputs.current_version == '1.11.3.Final' }}
        echo ${{ steps.pom-details.outputs.project_group == 'org.acme' }}
        echo ${{ steps.pom-details.outputs.project_name == 'code-with-quarkus' }}
        echo ${{ steps.pom-details.outputs.quarkus_extensions == 'io.quarkus:quarkus-arc,io.quarkus:quarkus-junit5' }}

    - name: Test Action using provided filename
      id: pom-details-filename
      uses: ./ # Local action
      with:
        filename: pom.xml

    - name: Check values
      run: |
        echo ${{ steps.pom-details-filename.outputs.current_version }}
        echo ${{ steps.pom-details-filename.outputs.project_group }}
        echo ${{ steps.pom-details-filename.outputs.project_name }}
        echo ${{ steps.pom-details-filename.outputs.quarkus_extensions }}