# Test GitHub action

name: Test GitHub Action
on: [push]
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Test Action using default filename
      id: pom-details
      uses: jthambly/quarkus-pom-action@v1

    - name: Check values
      run: |
        echo ${{ steps.pom-details.outputs.current_version }}
        echo ${{ steps.pom-details.outputs.project_group }}
        echo ${{ steps.pom-details.outputs.project_name }}
        echo ${{ steps.pom-details.outputs.quarkus_extensions }}

    - name: Test Action using provided filename
      id: pom-details-filename
      uses: jthambly/quarkus-pom-action@v1
      with:
        filename: pom.xml