# Test GitHub action

name: Test GitHub Action
on: [push]
jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Test Action using default filename
      id: pom-details
      uses: jthambly/quarkus-pom-action
    - name: Test Action using providing filename
      id: pom-details-filename
      uses: jthambly/quarkus-pom-action
      with:
        filename: pom.xml